import { 
  MobileProduct, 
  Customer, 
  MobileUser, 
  StockTransfer, 
  OutboxMutation, 
  MobileSalesOrder, 
  StockMovement, 
  Supplier, 
  PurchaseOrder 
} from './types';

export const mockUsers: MobileUser[] = [
  {
    id: 'usr_sarah',
    name: 'Sarah Jenkins',
    nameAr: 'سارة جينكينز',
    role: 'CASHIER',
    pin: '1234',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    storeId: 'str_main',
    storeName: 'Downtown Flagship Branch',
  },
  {
    id: 'usr_alex',
    name: 'Alex Rivera',
    nameAr: 'أليكس ريفيرا',
    role: 'STORE_MANAGER',
    pin: '5678',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    storeId: 'str_main',
    storeName: 'Downtown Flagship Branch',
  },
  {
    id: 'usr_tariq',
    name: 'Tariq Al-Mansoor',
    nameAr: 'طارق المنصور',
    role: 'ADMIN',
    pin: '9999',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    storeId: 'str_main',
    storeName: 'Downtown Flagship Branch',
  }
];

export const mockCategories = [
  { id: 'all', name: 'All Items', nameAr: 'جميع المنتجات', icon: 'LayoutGrid' },
  { id: 'fav', name: 'Favorites ⭐', nameAr: 'المفضلة ⭐', icon: 'Star' },
  { id: 'beverages', name: 'Beverages', nameAr: 'المشروبات', icon: 'Coffee' },
  { id: 'bakery', name: 'Bakery', nameAr: 'المخبوزات', icon: 'Croissant' },
  { id: 'grocery', name: 'Grocery', nameAr: 'البقالة', icon: 'ShoppingBag' },
  { id: 'dairy', name: 'Dairy & Fresh', nameAr: 'الألبان والطازج', icon: 'Milk' },
  { id: 'snacks', name: 'Snacks & Sweets', nameAr: 'الوجبات الخفيفة', icon: 'Cookie' },
  { id: 'combos', name: 'Combos & Meals', nameAr: 'الوجبات المجمعة', icon: 'Utensils' },
];

export const mockProducts: MobileProduct[] = [
  {
    id: 'prod_espresso',
    code: 'BEV-001',
    name: 'Artisan Espresso Roast',
    nameAr: 'إسبريسو محمص فاخر',
    category: 'beverages',
    categoryAr: 'المشروبات',
    isTaxable: true,
    isFavorite: true,
    color: 'from-amber-600 to-amber-800',
    icon: 'Coffee',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_esp_single',
        productId: 'prod_espresso',
        sku: 'BEV-ESP-SGL',
        barcode: '890103000101',
        variantName: 'Single Shot',
        variantNameAr: 'شوت فردي',
        retailPrice: 3.50,
        costPrice: 0.80,
        minPrice: 3.00,
        stockOnHand: 450,
        reorderPoint: 50,
      },
      {
        id: 'var_esp_double',
        productId: 'prod_espresso',
        sku: 'BEV-ESP-DBL',
        barcode: '890103000102',
        variantName: 'Double Shot (Doppio)',
        variantNameAr: 'شوت مزدوج (دوبيو)',
        retailPrice: 4.50,
        costPrice: 1.10,
        minPrice: 4.00,
        stockOnHand: 380,
        reorderPoint: 50,
      }
    ]
  },
  {
    id: 'prod_latte',
    code: 'BEV-002',
    name: 'Vanilla Oat Milk Latte',
    nameAr: 'لاتيه الفانيليا بحليب الشوفان',
    category: 'beverages',
    categoryAr: 'المشروبات',
    isTaxable: true,
    isFavorite: true,
    color: 'from-amber-500 to-orange-600',
    icon: 'Coffee',
    image: 'https://images.unsplash.com/photo-1534778101976-62847782c213?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_lat_med',
        productId: 'prod_latte',
        sku: 'BEV-LAT-12OZ',
        barcode: '890103000111',
        variantName: 'Regular 12oz',
        variantNameAr: 'وسط 12 أونصة',
        retailPrice: 5.25,
        costPrice: 1.40,
        minPrice: 4.75,
        stockOnHand: 220,
        reorderPoint: 30,
      },
      {
        id: 'var_lat_lrg',
        productId: 'prod_latte',
        sku: 'BEV-LAT-16OZ',
        barcode: '890103000112',
        variantName: 'Large 16oz',
        variantNameAr: 'كبير 16 أونصة',
        retailPrice: 6.00,
        costPrice: 1.75,
        minPrice: 5.50,
        stockOnHand: 180,
        reorderPoint: 30,
      }
    ]
  },
  {
    id: 'prod_croissant',
    code: 'BAK-001',
    name: 'French Butter Croissant',
    nameAr: 'كرواسون الزبدة الفرنسي',
    category: 'bakery',
    categoryAr: 'المخبوزات',
    isTaxable: true,
    isFavorite: true,
    color: 'from-yellow-600 to-amber-700',
    icon: 'Croissant',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_cro_plain',
        productId: 'prod_croissant',
        sku: 'BAK-CRO-PLN',
        barcode: '890103000201',
        variantName: 'Plain Butter',
        variantNameAr: 'سادة بالزبدة',
        retailPrice: 3.75,
        costPrice: 1.10,
        minPrice: 3.25,
        stockOnHand: 35,
        reorderPoint: 15,
      },
      {
        id: 'var_cro_almond',
        productId: 'prod_croissant',
        sku: 'BAK-CRO-ALM',
        barcode: '890103000202',
        variantName: 'Toasted Almond',
        variantNameAr: 'باللوز المحمص',
        retailPrice: 4.50,
        costPrice: 1.45,
        minPrice: 4.00,
        stockOnHand: 8, // Low stock trigger
        reorderPoint: 15,
      }
    ]
  },
  {
    id: 'prod_sourdough',
    code: 'BAK-002',
    name: 'Artisan Rustic Sourdough',
    nameAr: 'خبز العجين المخمر الريفي',
    category: 'bakery',
    categoryAr: 'المخبوزات',
    isTaxable: false, // staple food 0% tax
    isFavorite: false,
    color: 'from-amber-700 to-stone-800',
    icon: 'Wheat',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_srd_whole',
        productId: 'prod_sourdough',
        sku: 'BAK-SRD-WHL',
        barcode: '890103000211',
        variantName: 'Whole Loaf 800g',
        variantNameAr: 'رغيف كامل 800 جم',
        retailPrice: 7.50,
        costPrice: 2.20,
        minPrice: 6.50,
        stockOnHand: 14,
        reorderPoint: 10,
      }
    ]
  },
  {
    id: 'prod_orange_juice',
    code: 'BEV-003',
    name: 'Fresh Squeezed Orange Juice',
    nameAr: 'عصير برتقال طازج معصور',
    category: 'beverages',
    categoryAr: 'المشروبات',
    isTaxable: true,
    isFavorite: true,
    color: 'from-orange-500 to-amber-500',
    icon: 'Citrus',
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_oj_500ml',
        productId: 'prod_orange_juice',
        sku: 'BEV-OJ-500',
        barcode: '890103000121',
        variantName: 'Cold Bottle 500ml',
        variantNameAr: 'زجاجة مبردة 500 مل',
        retailPrice: 4.80,
        costPrice: 1.50,
        minPrice: 4.20,
        stockOnHand: 6, // Low stock
        reorderPoint: 20,
      }
    ]
  },
  {
    id: 'prod_organic_milk',
    code: 'DRY-001',
    name: 'Farm Fresh Organic Whole Milk',
    nameAr: 'حليب كامل الدسم عضوي طازج',
    category: 'dairy',
    categoryAr: 'الألبان والطازج',
    isTaxable: false,
    isFavorite: false,
    color: 'from-blue-400 to-indigo-600',
    icon: 'Milk',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_milk_1l',
        productId: 'prod_organic_milk',
        sku: 'DRY-MLK-1L',
        barcode: '890103000301',
        variantName: '1 Liter Bottle',
        variantNameAr: 'زجاجة 1 لتر',
        retailPrice: 3.20,
        costPrice: 1.80,
        minPrice: 2.90,
        stockOnHand: 48,
        reorderPoint: 15,
      }
    ]
  },
  {
    id: 'prod_greek_yogurt',
    code: 'DRY-002',
    name: 'Authentic Greek Strained Yogurt',
    nameAr: 'زبادي يوناني أصلي مصفى',
    category: 'dairy',
    categoryAr: 'الألبان والطازج',
    isTaxable: false,
    isFavorite: false,
    color: 'from-sky-500 to-blue-700',
    icon: 'Layers',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_ygt_500g',
        productId: 'prod_greek_yogurt',
        sku: 'DRY-YGT-500',
        barcode: '890103000311',
        variantName: '500g Tub',
        variantNameAr: 'عبوة 500 جم',
        retailPrice: 4.95,
        costPrice: 2.10,
        minPrice: 4.25,
        stockOnHand: 32,
        reorderPoint: 12,
      }
    ]
  },
  {
    id: 'prod_breakfast_combo',
    code: 'CMB-001',
    name: 'Morning Power Breakfast Combo',
    nameAr: 'وجبة إفطار الصباح المتكاملة',
    category: 'combos',
    categoryAr: 'الوجبات المجمعة',
    isTaxable: true,
    isFavorite: true,
    color: 'from-emerald-500 to-teal-700',
    icon: 'Utensils',
    image: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_cmb_std',
        productId: 'prod_breakfast_combo',
        sku: 'CMB-BRK-STD',
        barcode: '890103000501',
        variantName: 'Latte + Butter Croissant + Fruit Cup',
        variantNameAr: 'لاتيه + كرواسون + سلطة فواكه',
        retailPrice: 9.99,
        costPrice: 3.20,
        minPrice: 8.99,
        stockOnHand: 99,
        reorderPoint: 20,
      }
    ]
  },
  {
    id: 'prod_dark_chocolate',
    code: 'SNK-001',
    name: 'Single Origin Dark Chocolate 72%',
    nameAr: 'شوكولاتة داكنة نقية 72%',
    category: 'snacks',
    categoryAr: 'الوجبات الخفيفة',
    isTaxable: true,
    isFavorite: false,
    color: 'from-amber-900 to-stone-900',
    icon: 'Cookie',
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_choc_bar',
        productId: 'prod_dark_chocolate',
        sku: 'SNK-CHC-100',
        barcode: '890103000401',
        variantName: '100g Artisan Bar',
        variantNameAr: 'لوح شوكولاتة 100 جم',
        retailPrice: 4.25,
        costPrice: 1.60,
        minPrice: 3.80,
        stockOnHand: 65,
        reorderPoint: 15,
      }
    ]
  },
  {
    id: 'prod_sparkling_water',
    code: 'BEV-004',
    name: 'San Pellegrino Mineral Water',
    nameAr: 'مياه غازية معدنية فوارة',
    category: 'beverages',
    categoryAr: 'المشروبات',
    isTaxable: true,
    isFavorite: false,
    color: 'from-teal-600 to-emerald-800',
    icon: 'Droplets',
    image: 'https://images.unsplash.com/photo-1559839914-ba2c6114a13e?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_water_750',
        productId: 'prod_sparkling_water',
        sku: 'BEV-WAT-750',
        barcode: '890103000131',
        variantName: 'Glass Bottle 750ml',
        variantNameAr: 'زجاجة زجاجية 750 مل',
        retailPrice: 3.50,
        costPrice: 1.10,
        minPrice: 3.00,
        stockOnHand: 92,
        reorderPoint: 24,
      }
    ]
  },
  {
    id: 'prod_olive_oil',
    code: 'GRO-001',
    name: 'Extra Virgin Cold Pressed Olive Oil',
    nameAr: 'زيت زيتون بكر ممتاز معصور على البارد',
    category: 'grocery',
    categoryAr: 'البقالة',
    isTaxable: false,
    isFavorite: false,
    color: 'from-lime-600 to-emerald-800',
    icon: 'FlaskConical',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=80',
    variants: [
      {
        id: 'var_oil_500ml',
        productId: 'prod_olive_oil',
        sku: 'GRO-OIL-500',
        barcode: '890103000601',
        variantName: 'Glass Bottle 500ml',
        variantNameAr: 'زجاجة 500 مل',
        retailPrice: 12.50,
        costPrice: 6.80,
        minPrice: 11.00,
        stockOnHand: 28,
        reorderPoint: 10,
      }
    ]
  }
];

export const mockCustomers: Customer[] = [
  {
    id: 'cust_walkin',
    code: 'CUST-000',
    name: 'Walk-In Customer (Default)',
    nameAr: 'عميل عام / مباشر',
    phone: '---',
    email: '',
    creditLimit: 0,
    creditBalance: 0,
    loyaltyPoints: 0,
    tier: 'REGULAR',
    totalSpend: 0,
    totalVisits: 0,
  },
  {
    id: 'cust_omar',
    code: 'CUST-101',
    name: 'Omar Khader',
    nameAr: 'عمر خضر',
    phone: '+971 50 123 4567',
    email: 'omar.khader@example.com',
    creditLimit: 1500.00,
    creditBalance: 320.50,
    loyaltyPoints: 480,
    tier: 'VIP', // 10% auto-discount VIP level
    totalSpend: 1420.50,
    totalVisits: 18,
  },
  {
    id: 'cust_layla',
    code: 'CUST-102',
    name: 'Layla Al-Sayed',
    nameAr: 'ليلى السيد',
    phone: '+971 55 987 6543',
    email: 'layla.sayed@example.com',
    creditLimit: 500.00,
    creditBalance: 0,
    loyaltyPoints: 215,
    tier: 'SILVER',
    totalSpend: 540.00,
    totalVisits: 7,
  },
  {
    id: 'cust_david',
    code: 'CUST-103',
    name: 'David Chen',
    nameAr: 'ديفيد تشين',
    phone: '+1 415 555 0192',
    email: 'david.chen@example.com',
    creditLimit: 2000.00,
    creditBalance: 840.00,
    loyaltyPoints: 1250,
    tier: 'VIP',
    totalSpend: 3120.00,
    totalVisits: 34,
  }
];

export const initialSalesHistory: MobileSalesOrder[] = [
  {
    id: 'ord_1001',
    orderNumber: 'POS-2026-00101',
    offlineId: 'off_uuid_991823',
    storeId: 'str_main',
    cashierId: 'usr_sarah',
    cashierName: 'Sarah Jenkins',
    customerId: 'cust_omar',
    customerName: 'Omar Khader',
    items: [
      {
        id: 'ci_1',
        productId: 'prod_espresso',
        variantId: 'var_esp_double',
        productName: 'Artisan Espresso Roast',
        productNameAr: 'إسبريسو محمص فاخر',
        variantName: 'Double Shot (Doppio)',
        variantNameAr: 'شوت مزدوج',
        sku: 'BEV-ESP-DBL',
        barcode: '890103000102',
        unitPrice: 4.50,
        costPrice: 1.10,
        quantity: 2,
        discountType: 'percentage',
        discountValue: 10,
        isTaxable: true,
      },
      {
        id: 'ci_2',
        productId: 'prod_croissant',
        variantId: 'var_cro_plain',
        productName: 'French Butter Croissant',
        productNameAr: 'كرواسون الزبدة الفرنسي',
        variantName: 'Plain Butter',
        variantNameAr: 'سادة بالزبدة',
        sku: 'BAK-CRO-PLN',
        barcode: '890103000201',
        unitPrice: 3.75,
        costPrice: 1.10,
        quantity: 1,
        discountType: 'percentage',
        discountValue: 0,
        isTaxable: true,
      }
    ],
    subtotalAmount: 11.85,
    discountAmount: 0.90,
    taxAmount: 0.90,
    grandTotal: 11.85,
    paidAmount: 15.00,
    changeAmount: 3.15,
    payments: [{ method: 'CASH', amount: 15.00 }],
    status: 'COMPLETED',
    loyaltyPointsEarned: 11,
    loyaltyPointsRedeemed: 0,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    syncStatus: 'SYNCED',
    idempotencyKey: 'idemp_ord_1001',
  },
  {
    id: 'ord_1002',
    orderNumber: 'POS-2026-00102',
    offlineId: 'off_uuid_991824',
    storeId: 'str_main',
    cashierId: 'usr_sarah',
    cashierName: 'Sarah Jenkins',
    customerId: 'cust_layla',
    customerName: 'Layla Al-Sayed',
    items: [
      {
        id: 'ci_3',
        productId: 'prod_breakfast_combo',
        variantId: 'var_cmb_std',
        productName: 'Morning Power Breakfast Combo',
        productNameAr: 'وجبة إفطار الصباح المتكاملة',
        variantName: 'Standard Meal',
        variantNameAr: 'وجبة قياسية',
        sku: 'CMB-BRK-STD',
        barcode: '890103000501',
        unitPrice: 9.99,
        costPrice: 3.20,
        quantity: 1,
        discountType: 'percentage',
        discountValue: 0,
        isTaxable: true,
      }
    ],
    subtotalAmount: 9.99,
    discountAmount: 0,
    taxAmount: 0.82,
    grandTotal: 10.81,
    paidAmount: 10.81,
    changeAmount: 0,
    payments: [{ method: 'CARD', amount: 10.81, cardLast4: '4242' }],
    status: 'COMPLETED',
    loyaltyPointsEarned: 10,
    loyaltyPointsRedeemed: 0,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    syncStatus: 'SYNCED',
    idempotencyKey: 'idemp_ord_1002',
  }
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'mov_1',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    variantId: 'var_esp_double',
    productName: 'Artisan Espresso Roast',
    variantName: 'Double Shot',
    sku: 'BEV-ESP-DBL',
    type: 'SALE',
    quantityDelta: -2,
    unitCost: 1.10,
    referenceId: 'POS-2026-00101',
    sourceLocation: 'Store Front',
    destinationLocation: 'Customer',
    actor: 'Sarah Jenkins',
  },
  {
    id: 'mov_2',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    variantId: 'var_cro_plain',
    productName: 'French Butter Croissant',
    variantName: 'Plain Butter',
    sku: 'BAK-CRO-PLN',
    type: 'SALE',
    quantityDelta: -1,
    unitCost: 1.10,
    referenceId: 'POS-2026-00101',
    sourceLocation: 'Store Front',
    destinationLocation: 'Customer',
    actor: 'Sarah Jenkins',
  },
  {
    id: 'mov_3',
    timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    variantId: 'var_cro_plain',
    productName: 'French Butter Croissant',
    variantName: 'Plain Butter',
    sku: 'BAK-CRO-PLN',
    type: 'PURCHASE',
    quantityDelta: 40,
    unitCost: 1.10,
    referenceId: 'PO-2026-0042',
    sourceLocation: 'Supplier: Golden Bakery',
    destinationLocation: 'Store Front',
    actor: 'Alex Rivera',
    note: 'Morning fresh batch receiving',
  }
];

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup_roaster',
    name: 'Artisan Coffee Roasters Ltd',
    contactPerson: 'David Miller',
    phone: '+1 415 889 0192',
    email: 'orders@artisancoffee.io',
    address: '450 Roastery Way, Seattle, WA',
    paymentTerms: 'NET 30',
  },
  {
    id: 'sup_bakery',
    name: 'Golden Crust Artisan Bakery',
    contactPerson: 'Sophie Laurent',
    phone: '+1 415 772 3849',
    email: 'sophie@goldencrust.fr',
    address: '120 Boulangerie Blvd, SF, CA',
    paymentTerms: 'COD',
  },
  {
    id: 'sup_dairy',
    name: 'Green Valley Organic Farms',
    contactPerson: 'Mark Peterson',
    phone: '+1 415 663 9921',
    email: 'supplies@greenvalleydairy.com',
    address: '88 Meadow Road, Sonoma, CA',
    paymentTerms: 'NET 15',
  }
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po_001',
    poNumber: 'PO-2026-0042',
    supplierId: 'sup_roaster',
    supplierName: 'Artisan Coffee Roasters Ltd',
    destinationStore: 'Downtown Flagship Store',
    status: 'ORDERED',
    orderDate: '2026-08-20',
    expectedDate: '2026-08-28',
    totalCost: 1240.00,
    items: [
      {
        id: 'poi_1',
        variantId: 'var_esp_single',
        productName: 'Artisan Espresso Roast',
        variantName: 'Single Shot Bean Batch',
        sku: 'BEV-ESP-SGL',
        quantityOrdered: 500,
        quantityReceived: 0,
        unitCost: 0.80,
      },
      {
        id: 'poi_2',
        variantId: 'var_esp_double',
        productName: 'Artisan Espresso Roast',
        variantName: 'Double Shot Bean Batch',
        sku: 'BEV-ESP-DBL',
        quantityOrdered: 400,
        quantityReceived: 0,
        unitCost: 1.10,
      }
    ]
  },
  {
    id: 'po_002',
    poNumber: 'PO-2026-0041',
    supplierId: 'sup_bakery',
    supplierName: 'Golden Crust Artisan Bakery',
    destinationStore: 'Downtown Flagship Store',
    status: 'RECEIVED',
    orderDate: '2026-08-19',
    expectedDate: '2026-08-20',
    totalCost: 245.50,
    items: [
      {
        id: 'poi_3',
        variantId: 'var_cro_plain',
        productName: 'French Butter Croissant',
        variantName: 'Plain Butter',
        sku: 'BAK-CRO-PLN',
        quantityOrdered: 50,
        quantityReceived: 50,
        unitCost: 1.10,
      }
    ]
  }
];

export const mockOutboxMutations: OutboxMutation[] = [
  {
    id: 'mut_101',
    operationId: 'op_sync_001',
    entityType: 'SALES_ORDER',
    entityId: 'ord_1001',
    action: 'CREATE',
    payload: initialSalesHistory[0],
    deviceId: 'DEVICE_SUNMI_V2_001',
    userId: 'usr_sarah',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    status: 'SYNCED',
    retryCount: 0,
    idempotencyKey: 'idemp_ord_1001',
  },
  {
    id: 'mut_102',
    operationId: 'op_sync_002',
    entityType: 'SALES_ORDER',
    entityId: 'ord_1002',
    action: 'CREATE',
    payload: initialSalesHistory[1],
    deviceId: 'DEVICE_SUNMI_V2_001',
    userId: 'usr_sarah',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    status: 'SYNCED',
    retryCount: 0,
    idempotencyKey: 'idemp_ord_1002',
  }
];

export const initialTransfers: StockTransfer[] = [
  {
    id: 'trf_101',
    transferNumber: 'TRF-2026-0008',
    sourceStoreId: 'wh_central',
    sourceStoreName: 'Central DC Warehouse',
    destStoreId: 'str_main',
    destStoreName: 'Downtown Flagship Branch',
    status: 'RECEIVED',
    items: [
      {
        variantId: 'var_esp_single',
        productName: 'Artisan Espresso Roast',
        sku: 'BEV-ESP-SGL',
        quantity: 200,
      },
      {
        variantId: 'var_lat_med',
        productName: 'Vanilla Oat Milk Latte',
        sku: 'BEV-LAT-12OZ',
        quantity: 100,
      }
    ],
    createdAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    dispatchedAt: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    receivedAt: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
  {
    id: 'trf_102',
    transferNumber: 'TRF-2026-0009',
    sourceStoreId: 'wh_central',
    sourceStoreName: 'Central DC Warehouse',
    destStoreId: 'str_main',
    destStoreName: 'Downtown Flagship Branch',
    status: 'DISPATCHED',
    items: [
      {
        variantId: 'var_cro_almond',
        productName: 'French Butter Croissant (Almond)',
        sku: 'BAK-CRO-ALM',
        quantity: 50,
      },
      {
        variantId: 'var_oj_500ml',
        productName: 'Fresh Squeezed Orange Juice',
        sku: 'BEV-OJ-500',
        quantity: 60,
      }
    ],
    createdAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    dispatchedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  }
];

export const mockSalesOrders = initialSalesHistory;
export const mockStockMovements = initialStockMovements;
export const mockStockTransfers = initialTransfers;

